export const DATA = [
  {
    id: "1",
    title: "Castle Hill Montessori Academy",
    content: "Lorem ipsum dolor sit amet",
    address: "Kerrs Road, Castle Hill, NSW 2154",
    children: "90 childrens",
    waitlist: 48,
    service: 4,
    base: "KindiCare Basic",
    Image:
      "https://cdn.nguyenkimmall.com/images/detailed/555/may-anh-cho-nguoi-moi.jpg",
  },
  {
    id: "2",
    title: "First Item",
    content: "Lorem ipsum dolor sit amet",
    address: "1 Kerrs Road, Castle Hill, NSW 2154",
    children: "34 childrens",
    waitlist: 58,
    service: 4,
    base: "KindiCare Basic",
    Image: "https://hc.com.vn/i/ecommerce/media/ckeditor_3087086.jpg",
  },
  {
    id: "3",
    title: "First Item",
    content: "Lorem ipsum dolor sit amet",
    address: "1 Kerrs Road, Castle Hill, NSW 2154",
    children: "34 childrens",
    waitlist: 58,
    service: 4,
    base: "KindiCare Basic",
    Image: "https://picsum.photos/700",
  },
];
